[site]
title = "Yiqing Wang"
description = "PhD student at Shanghai Jiao Tong University."
favicon = "/favicon.svg"
last_updated = "August 29, 2026"

[author]
name = "Yiqing Wang"
title = "PhD Student"
institution = "Shanghai Jiao Tong University"
avatar = "/nailong_bread.jpg"

[social]
# Contact information (leave blank or delete to hide)

google_scholar = "https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AKCpqFxj_aUPn7MS2m8aw-bXJ9Pqn-GDXvDYt3XYFOITAbpOPCg1wCSRCvTnPiUoYEYUnCYyGZ13ObqvGq-FP9u2RqZn4EfRnj_4gyPF_Iw&user=tmVwt00AAAAJ"
github = "https://github.com/Yeezie6"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href="/publications"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Internship"
type = "page"
target = "teaching"
href = "/teaching"
